name: Build and  push bbmp producer

on:
  push:
    paths:
      - 'Portal/Backend/bms-producer/**'
      - '!./**'
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
      env:
        DOCKER_USER: ${{ sercrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD     

    - name: docker build
      working-directory: ./Portal/Backend/bms-producer
      run: |
        docker build . -t egovio/bbmp-producer:latest

    - name: docker push
      run: |
        docker push egovio/bbmp-producer:latest
